Move calling to admin api to external file

diff --git a/bin/parts/for-all-sites b/bin/parts/for-all-sites
--- a/bin/parts/for-all-sites
+++ b/bin/parts/for-all-sites
@@ -1,23 +1,26 @@
 #!/bin/bash
-CONFIG_FILE=".multisite/config.yaml"
 
-# check if yq is installed
-if ! command -v yq &> /dev/null
-then
-    echo "yq could not be found, please install it first."
-    exit 1
-fi
+callSendRequestForAllSites() {
+  CONFIG_FILE=".multisite/config.yaml"
 
-# read sites from the config file
-SITES=$(yq e '.sites | keys' "$CONFIG_FILE" | sed 's/- //g')
+  # check if yq is installed
+  if ! command -v yq &> /dev/null
+  then
+      echo "yq could not be found, please install it first."
+      exit 1
+  fi
 
-# send request for default repository
-send_request "eds-eder-main"
+  # read sites from the config file
+  SITES=$(yq e '.sites | keys' "$CONFIG_FILE" | sed 's/- //g')
 
-# iterate over each site and send request
-for SITE in $SITES; do
-    ORIGIN=$(yq e ".sites.$SITE.origin" "$CONFIG_FILE")
-    REPO_NAME=$(basename "$ORIGIN" .git)
+  # send request for default repository
+  sendRequest "eds-eder-main"
 
-    send_request "$REPO_NAME"
-done
+  # iterate over each site and send request
+  for SITE in $SITES; do
+      ORIGIN=$(yq e ".sites.$SITE.origin" "$CONFIG_FILE")
+      REPO_NAME=$(basename "$ORIGIN" .git)
+
+      sendRequest "$REPO_NAME"
+  done
+}
